build:
  tags:
    - localhost-shared
  stage: build
  variables:
    ANKA_CLOUD_TEMPLATE_ID: "5d1b40b9-7e68-4807-a290-c59c66e926b4"
  script:
    - hostname
    - echo "Echo from inside of the VM!"
    - sleep 120
