test:
  tags:
    - localhost-shared
  script:
    - hostname
    - echo "Echo from inside of the VM!"
    - sleep 120

build:
  tags:
    - localhost-specific
  script:
    - hostname
    - echo "Echo from inside of the VM!"
    - sleep 120
