build:
  tags:
    - localhost-shared
  stage: build
  variables:
    ANKA_CLOUD_TEMPLATE_ID: "c12ccfa5-8757-411e-9505-128190e9854e"
    ANKA_CLOUD_TEMPLATE_TAG: "v1"
  script:
    - hostname
    - echo "Echo from inside of the VM!"
    - sleep 20

test:
  tags:
    - localhost-specific
  stage: test
  needs: ["build"]
  variables:
    ANKA_CLOUD_TEMPLATE_ID: "c12ccfa5-8757-411e-9505-128190e9854e"
    ANKA_CLOUD_TEMPLATE_TAG: "v1-with-file"
  script:
    - cat /etc/hosts
    - cat /Users/anka/Desktop/test.file
    - hostname
    - echo "Echo from inside of the VM!"
    - sleep 20
