build:
  tags:
    - localhost-shared
  stage: build
  variables:
    ANKA_TEMPLATE_UUID: "c0847bc9-5d2d-4dbc-ba6a-240f7ff08032"
    ANKA_TAG_NAME: "base:port-forward-22:brew-git:gitlab"
  script:
    - hostname
    - echo "Echo from inside of the VM!"

test:
  tags:
    - localhost-specific
  stage: test
  needs: ["build"]
  variables:
    ANKA_TEMPLATE_UUID: "c0847bc9-5d2d-4dbc-ba6a-240f7ff08032"
    ANKA_TAG_NAME: "base:port-forward-22:brew-git:gitlab-with-file"
  script:
    - cat /etc/hosts
    - cat /Users/anka/Desktop/test.file
    - hostname
    - echo "Echo from inside of the VM!"
