test:
  tags:
    - localhost-shared
  stage: test
  script:
    - hostname
    - echo "Echo from inside of the VM!"
    - exit 10

build:
  tags:
    - localhost-specific
  stage: build
  script:
    - hostname
    - echo "Echo from inside of the VM!"
