build:
  tags:
    - localhost-shared
  stage: build
  variables:
    ANKA_TEMPLATE_UUID: "5d1b40b9-7e68-4807-a290-c59c66e926b4"
    ANKA_TAG_NAME: "v1"
  script:
    - hostname
    - echo "Echo from inside of the VM!"

test:
  tags:
    - localhost-specific
  stage: test
  needs: ["build"]
  variables:
    ANKA_TEMPLATE_UUID: "5d1b40b9-7e68-4807-a290-c59c66e926b4"
    ANKA_TAG_NAME: "v1-with-file"
  script:
    - cat /etc/hosts
    - cat /Users/anka/Desktop/test.file
    - hostname
    - echo "Echo from inside of the VM!"
