test:
  tags:
    - localhost-shared
  script:
    - hostname
    - echo "Echo from inside of the VM!"

build:
  tags:
    - localhost-specific
  script:
    - hostname
    - echo "Echo from inside of the VM!"